# Generated by Django 4.0.8 on 2023-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.CharField(blank=True, choices=[('kakao', 'Kakao'), ('github', 'Github')], default=None, max_length=10, null=True),
        ),
    ]
