# Generated by Django 4.1.1 on 2022-12-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_room_amenities_alter_room_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="check_in",
            new_name="check_in_time",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="check_out",
            new_name="check_out_time",
        ),
    ]
