# Generated by Django 4.1.1 on 2022-12-19 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_rename_check_in_room_check_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="check_in_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="check_out_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
