databases:
  - name: djangoproject
    databaseName: djangoproject
    user: djangoproject
    region: singapore

services:
  - type: web
    name: djangoproject
    env: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn djangoproject.wsgi:application'
    region: singapore
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djangoproject
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
