# Generated by Django 4.1.1 on 2022-12-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_rename_end_experience_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start",
            field=models.TimeField(),
        ),
    ]
