# Generated by Django 4.1.1 on 2022-12-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0004_alter_photo_file_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
