# Generated by Django 4.1.1 on 2022-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_experience_alter_booking_room_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="experience_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="experience_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
